### ISSUE TITLE
v 6.2.17 Error during Swaparr processing for Ebooks: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by sleighton** [plexguide/Huntarr.io#321]
Getting this error in multiple apps from swapparr.

```
2025-05-05 14:59:31 - huntarr.readarr - INFO - Found 0 unprocessed books out of 10 total books eligible for upgrade.
2025-05-05 14:59:31 - huntarr.readarr - INFO - No unprocessed books found for Ebooks. All available books have been processed.
2025-05-05 14:59:32 - huntarr.readarr - INFO - Running Swaparr on readarr instance: Ebooks
2025-05-05 14:59:32 - huntarr.readarr - ERROR - Error during Swaparr processing for Ebooks: 'str' object has no attribute 'get'
return parse_queue_items(all_records, "book", app_name)
```

**Comment by Admin9705** [comment]
@sleighton can you let me know if this work 6.2.18 - https://github.com/plexguide/Huntarr.io/releases/tag/6.2.18

**Comment by sleighton** [comment]
Looks like you nailed it, not seeing the error in 6.2.18

**Comment by Admin9705** [comment]
@sleighton thanks for really helping.

**Comment by Admin9705** [comment]
has to be reopened due to revert

**Comment by Admin9705** [comment]
will work in 6.2.20 @sleighton
